on:
  push:
  pull_request:
   types: [opened]

jobs:
  check-pr-description:
    runs-on: ubuntu-20.04
    steps:
    - name : Check Description of PR
      if: ${{ github.event.pull_request.body == '' }}
      run: |
        echo "ERROR: The Description of your PR must not be empty !"
        exit 1
